---
language: node_js
node_js:
  - "8"

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    - SCRIPT=test
    # - SCRIPT=test:fastboot
    # - SCRIPT=test:node

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install --no-lockfile --non-interactive

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn run $SCRIPT

after_script:
  - greenkeeper-lockfile-upload
